site_name: OpenAPI HTTPX
site_description: Generate a typed HTTPX client from an OpenAPI specification.
site_url: https://mrloh.github.io/openapi-httpx/
repo_url: https://github.com/MrLoh/openapi-httpx
repo_name: MrLoh/openapi-httpx
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Getting Started: index.md
  - Using the Client: client.md
  - Library Reference: reference.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
